//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// *** Warning: Please do not edit as changes will be overwritten. This file is auto generated. ***
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyCompany("Esri")]
[assembly: AssemblyProduct("ArcGIS Maps SDK for Unity")]
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.4561")]
[assembly: AssemblyCopyright("Copyright ©1999-2025 Esri Inc. All Rights Reserved")]

